login_login_login:
    path:     /login
    defaults: { _controller: LoginLoginBundle:Default:login }
    
login_login_signup:
    path:     /signup
    defaults: { _controller: LoginLoginBundle:Default:signup }

login_login_logout:
    path:     /logout
    defaults: { _controller: LoginLoginBundle:Default:logout }
    
login_login_welcome:
    path:     /welcome
    defaults: { _controller: LoginLoginBundle:Default:welcome }